Traceback (most recent call last):
  File "./hw5_parser.py", line 16, in <module>
    with open(sys.argv[2],'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/dropbox/22-23/au571/hw5/sentences.txt'
